### ISSUE TITLE
Error in predict.mvar

### ISSUE THREAD

**Issue by pesceele** [jmbh/mgmDocumentation#1]
Hi,

I'm receiving an error in the predict.mvar(object, data) of your code. In particular, in the first example, you pass to the function a matrix, but I receive the following error:

> pred_mgm <- predict(object = fit_mvar,  data = mvar_data$data, errorCon = c("RMSE", "R2"), errorCat = c("CC", "nCC"))
+ Error in model.frame.default(object, data, xlev = xlev) : 
  'data' must be a data.frame, not a matrix or an array

In this case the error makes sense, so I converted the mvar_data$data to a data.frame, but I get the same error. I also tried with my own data.frame and I get the same error again.

Thanks in advance

**Comment by jmbh** [comment]
I cannot reproduce your error. But I remember that I removed the matrix requirement a while ago. Could you check whether you are using the latest development version from Github? You can install it with

library(devtools)
install_github("jmbh/mgm")
