### ISSUE TITLE
Examining Model Fit Statistics

### ISSUE THREAD

**Issue by paganantonio** [jmbh/mgmDocumentation#2]
In your thorough and helpful article published in 2019, you indicate various functions such as resample and predict. Is there a function that can be used to examine the model fit of the tvmgm model? I know you use alpha-level to conclude significance of the model fit, but wondered if a method could be conducted to examine model fit by using BIC or AIC type metrics. 
Thanks!

**Comment by jmbh** [comment]
This issue was also posted here https://github.com/jmbh/mgm/issues/17
